# Generated by Django 2.2.3 on 2019-11-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('market_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.Market')),
            ],
        ),
    ]
