# Generated by Django 2.2.3 on 2019-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20191213_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
